
package sistemabiblioteca;
import static sistemabiblioteca.AppSistemaBiblioteca.con;
/**
 *
 * @author joefi
 */
public class AdminTools extends javax.swing.JFrame {

    /**
     * Creates new form AdminTools
     */
    public AdminTools() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registryAutorButton = new javax.swing.JButton();
        jButtonRegistrarLibro = new javax.swing.JButton();
        jButtonLocalidadNueva = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        registryAlmacenButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        registryAutorButton.setText("Registrar Autor");
        registryAutorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registryAutorButtonActionPerformed(evt);
            }
        });

        jButtonRegistrarLibro.setText("Registrar Libro");
        jButtonRegistrarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarLibroActionPerformed(evt);
            }
        });

        jButtonLocalidadNueva.setText("Registrar Localidad");
        jButtonLocalidadNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocalidadNuevaActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Registrar Editorial");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        registryAlmacenButton.setText("Registrar Almacen");
        registryAlmacenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registryAlmacenButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonRegistrarLibro)
                        .addGap(23, 23, 23)
                        .addComponent(registryAutorButton)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registryAlmacenButton)
                            .addComponent(jButtonLocalidadNueva))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registryAutorButton)
                    .addComponent(jButtonRegistrarLibro)
                    .addComponent(jButtonLocalidadNueva))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(registryAlmacenButton))
                .addContainerGap(222, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registryAutorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registryAutorButtonActionPerformed
        RegistryAutorUI raui = new RegistryAutorUI();
    }//GEN-LAST:event_registryAutorButtonActionPerformed

    private void jButtonRegistrarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarLibroActionPerformed
        new FormularioLibro(con).setVisible(true);
    }//GEN-LAST:event_jButtonRegistrarLibroActionPerformed

    private void jButtonLocalidadNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocalidadNuevaActionPerformed
        new FormularioLocalidad().setVisible(true);
    }//GEN-LAST:event_jButtonLocalidadNuevaActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
       RegistryEditorialUI reui= new RegistryEditorialUI();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void registryAlmacenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registryAlmacenButtonActionPerformed
        RegistryAlmacenUI raiui= new RegistryAlmacenUI();
    }//GEN-LAST:event_registryAlmacenButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminTools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminTools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminTools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminTools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminTools().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLocalidadNueva;
    private javax.swing.JButton jButtonRegistrarLibro;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton registryAlmacenButton;
    private javax.swing.JButton registryAutorButton;
    // End of variables declaration//GEN-END:variables
}
