/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabiblioteca;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import static sistemabiblioteca.LogIn.id;
import static sistemabiblioteca.AppSistemaBiblioteca.con;

/**
 *
 * @author joefi
 */
public class CheckOut extends javax.swing.JFrame {
    /**
     * Creates new form CheckOut
     */
    boolean onlyEbooks, papel,both;
    float total;
    String card;
    public CheckOut() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);      
    }
    
    public CheckOut(boolean onlyEbooks, boolean papel, boolean both, float total,String card) {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);   
        this.onlyEbooks = onlyEbooks;
        this.papel = papel;
        this.both = both;
        this.total = total;
        this.card = card;
        printMsg();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCheckOut = new javax.swing.JLabel();
        labelCompra = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCO = new javax.swing.JTable();
        labelPago = new javax.swing.JLabel();
        labelDireccion = new javax.swing.JLabel();
        Gracias = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelCheckOut.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        labelCheckOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCheckOut.setText("CHECK OUT");

        labelCompra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCompra.setText("Hola");

        tableCO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Titulo", "Descripcion", "Tipo", "Precio", "Cantidad", "Pagaste"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableCO);
        if (tableCO.getColumnModel().getColumnCount() > 0) {
            tableCO.getColumnModel().getColumn(0).setMinWidth(0);
            tableCO.getColumnModel().getColumn(0).setPreferredWidth(0);
            tableCO.getColumnModel().getColumn(0).setMaxWidth(0);
            tableCO.getColumnModel().getColumn(2).setMinWidth(0);
            tableCO.getColumnModel().getColumn(2).setPreferredWidth(0);
            tableCO.getColumnModel().getColumn(2).setMaxWidth(0);
        }

        labelPago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPago.setText("Pagaste $ 0.0 ");

        labelDireccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDireccion.setText("<html> Tus libros fisicos se enviarán a");

        Gracias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Gracias.setText("Gracias por tu compra.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCheckOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                    .addComponent(labelPago, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDireccion)
                    .addComponent(Gracias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCheckOut)
                .addGap(18, 18, 18)
                .addComponent(labelCompra)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelPago)
                .addGap(18, 18, 18)
                .addComponent(labelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Gracias)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Gracias;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCheckOut;
    private javax.swing.JLabel labelCompra;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelPago;
    private javax.swing.JTable tableCO;
    // End of variables declaration//GEN-END:variables
    
    public void addToTable(String row []){
        DefaultTableModel model =(DefaultTableModel)tableCO.getModel();
        model.addRow(row);
        tableCO.setModel(model);
    }
    
    public void printMsg(){
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT nombre,direccion,email FROM cliente WHERE id = "+id);
            while(rs.next()){
                labelCompra.setText("Hola "+rs.getString(1) +"compraste los siguientes articulos");
                if (onlyEbooks)
                    labelDireccion.setText("Tus libros digitales se enviarán a tu email "+rs.getString(3));
                else if(both)
                    labelDireccion.setText("<html> Tus libros fisicos se enviaran a tu dieccion "+rs.getString(2)+" "
                            + "y tus libros digitales se enviarán a tu email "+rs.getString(3));
                else if (papel)
                    labelDireccion.setText("Tus libros fisicos se enviaran a tu dieccion "+rs.getString(2));
            }
            st.close();
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(CheckOut.class.getName()).log(Level.SEVERE, null, ex);
        }
        labelPago.setText("Pagaste $ "+total+" con MASTERCARD **** **** **** "+card.substring(12, 16));
        
    }
}
