package sistemabiblioteca;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author joefi
 */
public class LibreriaUI extends javax.swing.JFrame {
    Connection con;
    /**
     * Creates new form LibreriaUI
     */
    public LibreriaUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonMysqlPP = new javax.swing.JButton();
        jButtonMysqlAndy = new javax.swing.JButton();
        jButtonMysqlVictor = new javax.swing.JButton();
        jButtonMysqlDiego = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonMysqlPP.setText("MySQL PP");
        jButtonMysqlPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMysqlPPActionPerformed(evt);
            }
        });

        jButtonMysqlAndy.setText("MySQL Andy");
        jButtonMysqlAndy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMysqlAndyActionPerformed(evt);
            }
        });

        jButtonMysqlVictor.setText("MySQL Victor");
        jButtonMysqlVictor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMysqlVictorActionPerformed(evt);
            }
        });

        jButtonMysqlDiego.setText("MySQL Diego");
        jButtonMysqlDiego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMysqlDiegoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonMysqlAndy)
                .addGap(186, 186, 186)
                .addComponent(jButtonMysqlDiego)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(jButtonMysqlPP)
                .addGap(168, 168, 168)
                .addComponent(jButtonMysqlVictor)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMysqlAndy)
                    .addComponent(jButtonMysqlVictor)
                    .addComponent(jButtonMysqlDiego)
                    .addComponent(jButtonMysqlPP))
                .addContainerGap(472, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMysqlAndyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMysqlAndyActionPerformed
        createConnection("Andy", "prueba");
    }//GEN-LAST:event_jButtonMysqlAndyActionPerformed

    private void jButtonMysqlPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMysqlPPActionPerformed
        createConnection("pepon", "admin");
    }//GEN-LAST:event_jButtonMysqlPPActionPerformed

    private void jButtonMysqlVictorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMysqlVictorActionPerformed
        createConnection("victornsn", "admin");
    }//GEN-LAST:event_jButtonMysqlVictorActionPerformed

    private void jButtonMysqlDiegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMysqlDiegoActionPerformed
        createConnection("root", "root");
    }//GEN-LAST:event_jButtonMysqlDiegoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibreriaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibreriaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibreriaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibreriaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibreriaUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMysqlAndy;
    private javax.swing.JButton jButtonMysqlDiego;
    private javax.swing.JButton jButtonMysqlPP;
    private javax.swing.JButton jButtonMysqlVictor;
    // End of variables declaration//GEN-END:variables
    
    public void createConnection(String user,String pass){
        String db="mydb", u=user, p=pass;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://25.13.55.58:3306/"+db, u, p );
            //jdbc:mysql://localhost:3306/?user=root
            System.out.println("Connection MYSQL database "+db+" succesful as "+u);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LibreriaUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(LibreriaUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
}
