package sistemabiblioteca;

/**
 *
 * @author Luna
 */

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class MostrarCliente extends javax.swing.JFrame {

    /**
     * Creates new form MostrarCliente
     */
    public MostrarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_MostrarCliente = new javax.swing.JTable();
        btn_Actualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tf_Idcliente = new javax.swing.JTextField();
        btn_actualiazar = new javax.swing.JButton();
        btn_Borrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        tf_domicilio = new javax.swing.JTextField();
        tf_apellidos = new javax.swing.JTextField();
        tf_telefono = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_mail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        tbl_MostrarCliente.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tbl_MostrarCliente.setFont(new java.awt.Font("Trajan Pro", 3, 14)); // NOI18N
        tbl_MostrarCliente.setForeground(new java.awt.Color(0, 153, 204));
        tbl_MostrarCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "idcliente", "Nombre", "Apellidos", "Domicilio", "Teléfono", "E-mail"
            }
        ));
        tbl_MostrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_MostrarClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_MostrarCliente);

        btn_Actualizar.setFont(new java.awt.Font("OCR A Std", 0, 13)); // NOI18N
        btn_Actualizar.setForeground(new java.awt.Color(255, 0, 51));
        btn_Actualizar.setText("Refrescar");
        btn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActualizarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Kozuka Mincho Pro", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setText("Idcliente");

        tf_Idcliente.setEditable(false);

        btn_actualiazar.setFont(new java.awt.Font("OCR A Std", 0, 13)); // NOI18N
        btn_actualiazar.setForeground(new java.awt.Color(255, 0, 51));
        btn_actualiazar.setText("Actualizar");
        btn_actualiazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualiazarActionPerformed(evt);
            }
        });

        btn_Borrar.setFont(new java.awt.Font("OCR A Std", 0, 13)); // NOI18N
        btn_Borrar.setForeground(new java.awt.Color(255, 0, 51));
        btn_Borrar.setText("Borrar");
        btn_Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BorrarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Kozuka Mincho Pro", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 51));
        jLabel3.setText("Nombre");

        jLabel5.setFont(new java.awt.Font("Kozuka Mincho Pro", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 51));
        jLabel5.setText("Apellidos");

        jLabel6.setFont(new java.awt.Font("Kozuka Mincho Pro", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 51));
        jLabel6.setText("Domicilio");

        jLabel7.setFont(new java.awt.Font("Kozuka Mincho Pro", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 51));
        jLabel7.setText("Telefono");

        jLabel2.setText("E-mail");

        tf_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_mailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(btn_Borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(btn_actualiazar)
                                .addGap(43, 43, 43)
                                .addComponent(btn_Actualizar)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tf_domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tf_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(162, 162, 162)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tf_Idcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(162, 162, 162)
                                        .addComponent(jLabel2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_apellidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_mail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Borrar)
                    .addComponent(btn_actualiazar)
                    .addComponent(btn_Actualizar))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tf_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tf_Idcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_MostrarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_MostrarClienteMouseClicked
        // TODO add your handling code here:
        int r = tbl_MostrarCliente.getSelectedRow();
        int id = (int) tbl_MostrarCliente.getValueAt(r, 0);
        String nombre = (String) tbl_MostrarCliente.getValueAt(r, 1);
        String apellidos = (String) tbl_MostrarCliente.getValueAt(r, 2);
        String direccion = (String) tbl_MostrarCliente.getValueAt(r, 3);
        String telefono = (String) tbl_MostrarCliente.getValueAt(r, 4);
        String mail = (String) tbl_MostrarCliente.getValueAt(r, 5);

        tf_Idcliente.setText("" + id);
        tf_nombre.setText(nombre);
        tf_apellidos.setText(apellidos);
        tf_domicilio.setText(direccion);
        tf_telefono.setText(telefono);
        tf_mail.setText(mail);

    }//GEN-LAST:event_tbl_MostrarClienteMouseClicked

    private void btn_BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BorrarActionPerformed
        // TODO add your handling code here:
        ClienteDTO cliente = new ClienteDTO();
        cliente.setIdcliente(Integer.parseInt(tf_Idcliente.getText()));

        int resp = JOptionPane.showConfirmDialog(null, "¿realmente desea eliminar?", "confirmar ELIMINACION", JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        if (resp == 0) {
            Conector cone = new Conector();
            ClienteDAO clientesDAO = new ClienteDAO(cone.miconector);
            int resultado = clientesDAO.borrarCliente(cliente);
            if (resultado > 0) {
                JOptionPane.showMessageDialog(null, "eliminacion erronia");
                refrescar();
            } else {
                JOptionPane.showMessageDialog(null, "eliminacion exitosa");
                refrescar();
                cone.cerrar();
            }
        }
    }//GEN-LAST:event_btn_BorrarActionPerformed

    private void tf_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_mailActionPerformed

    private void btn_actualiazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualiazarActionPerformed
        // TODO add your handling code here:
        ClienteDTO cliente = new ClienteDTO();
        cliente.setIdcliente(Integer.parseInt(tf_Idcliente.getText()));
        cliente.setNombre(tf_nombre.getText());
        cliente.setApellidos(tf_apellidos.getText());
        cliente.setDomicilio(tf_domicilio.getText());
        cliente.setTelefono(tf_telefono.getText());
        cliente.setMail(tf_mail.getText());

        int resp = JOptionPane.showConfirmDialog(null, "¿realmente desea modificar?", "confirmar actualizacion", JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        if (resp == 0) {
            Conector cone = new Conector();
            ClienteDAO clientesDAO = new ClienteDAO(cone.miconector);
            int resultado = clientesDAO.actulizarcliente(cliente);
            if (resultado > 0) {
                JOptionPane.showMessageDialog(null, "actualizacion exitosa");
                refrescar();
            } else {
                JOptionPane.showMessageDialog(null, "actualizacion erronia");
                cone.cerrar();
            }
        }
    }//GEN-LAST:event_btn_actualiazarActionPerformed

    private void btn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActualizarActionPerformed
        // TODO add your handling code here:
        refrescar();
    }//GEN-LAST:event_btn_ActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarCliente().setVisible(true);
            }
        });
    }
    
    
     private void refrescar() {
        Conector cone = new Conector();

        ClienteDAO clienteDAO = new ClienteDAO(cone.miconector);
        List<ClienteDTO> cliente = clienteDAO.clientegeneralDAO();

        DefaultTableModel modeloTabla = new DefaultTableModel();
        tbl_MostrarCliente.setModel(modeloTabla);

        modeloTabla.addColumn(" idcliente");
        modeloTabla.addColumn(" nombre");
        modeloTabla.addColumn(" apellidos");
        modeloTabla.addColumn(" domicilio");
        modeloTabla.addColumn(" telefono");
        modeloTabla.addColumn(" mail");

        Object[] columna = new Object[5];

        int objGuardados = cliente.size();

        for (int i = 0; i < objGuardados; i++) {
            columna[0] = cliente.get(i).getIdcliente();
            columna[1] = cliente.get(i).getNombre();
            columna[2] = cliente.get(i).getApellidos();
            columna[3] = cliente.get(i).getDomicilio();
            columna[4] = cliente.get(i).getTelefono();
            columna[5] = cliente.get(i).getMail();

            modeloTabla.addRow(columna);
        }
        cone.cerrar();
     }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Actualizar;
    private javax.swing.JButton btn_Borrar;
    private javax.swing.JButton btn_actualiazar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_MostrarCliente;
    private javax.swing.JTextField tf_Idcliente;
    private javax.swing.JTextField tf_apellidos;
    private javax.swing.JTextField tf_domicilio;
    private javax.swing.JTextField tf_mail;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_telefono;
    // End of variables declaration//GEN-END:variables
}



